resolver: nightly-2016-08-18

packages:
- '.'
- location:
    git: https://github.com/jwaldmann/wl-pprint-text
    commit: b6bd8ddc33925b4ead089bc6573db0e4b6e2ab4d
- location:
    git: https://github.com/jwaldmann/haskell-tpdb
    commit: c3eeb7b36733d057c52297c064f90ec5100c62f0

extra-deps:
- HaXml-1.25.3

flags: {}

extra-package-dbs: []

